name: L8D
title: L8D
author: Tenor Biel
description: A blog
url: http://l8d.github.io/
markdown: redcarpet
pygments: false

redcarpet:
  extensions: [
    tables,
    strikethrough,
    underline,
    highlight,
    footnotes,
    superscript,
    autolink,
    fenced_code_blocks
  ]
